### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by pmd2245** [thorikawa/camera-calibration-ios#3]
Hi,

First thank you for your work. 
I am trying to run your code but I systematically get the error: "Not Found" when directing the camera toward the grid. I have tested with regular chessboard circle grid, still get the same issue. 
After a short look at your program, it looks like the grid is not detected.
Do you have any idea about how I could solve the problem.
For information:
Xcode: 10.1
Platform target: iPhone X (12.1.4)
Language: Objective-C

Thanks

**Comment by thorikawa** [comment]
Did you try circle grid patter like this? https://github.com/thorikawa/camera-calibration-ios
it is documented in README.

**Comment by pmd2245** [comment]
Thanks for your answer.
I finally solved the problem. I was using the chessboard and the size did not fit the one defined in the code. 

If anyone wants to calibrate the camera using a chessboard, there are two options:
1- Find a chessboard image with 5x12 sub-squares
2- Go to the file Calibrator.cpp change the parameters of boardSize = cv::Size(X,Y) to fit your own chessboard. Let say you have a 6x8 sub-squares chessboard image then X=5 and Y=7.
